### ISSUE TITLE
Project Setup Description

### ISSUE THREAD

**Issue by peterdgreat** [peterdgreat/Space-Travellers-Hub#25]
We are a group of two people, You can find the link to the project setup below

[React Captsone Project](https://github.com/peterdgreat/Space-Travellers-Hub/projects/1)

**Comment by Lameck1** [comment]
Hi, @peterdgreat & @kensayo,

You've done well implementing your Kanban board 👏🏼. 

### Highlights:
- You've properly assigned yourselves tasks ✔️
- Task distribution is fair. The sums of points from your tasks are equal ✔️

You are now set to start working on the project, all the best 🙏🏼.

Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by peterdgreat** [comment]
Thanks
